/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceCategory = IDL.Variant({
  'pet' : IDL.Null,
  'birdsPoultry' : IDL.Null,
  'smallRuminant' : IDL.Null,
  'largeRuminant' : IDL.Null,
});
export const Time = IDL.Int;
export const ServiceType = IDL.Variant({
  'vaccination' : IDL.Null,
  'other' : IDL.Null,
  'treatment' : IDL.Null,
  'surgery' : IDL.Null,
  'consultation' : IDL.Null,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Text,
  'status' : AppointmentStatus,
  'clientName' : IDL.Text,
  'preferredDate' : Time,
  'category' : ServiceCategory,
  'serviceId' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'animalType' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : ServiceCategory,
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ServiceCategory, IDL.Text, Time],
      [],
      [],
    ),
  'cancelAppointment' : IDL.Func([IDL.Text], [], []),
  'createService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ServiceCategory, ServiceType, IDL.Nat],
      [],
      [],
    ),
  'deleteService' : IDL.Func([IDL.Text], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAppointment' : IDL.Func([IDL.Text], [Appointment], ['query']),
  'getAppointmentsByStatus' : IDL.Func(
      [AppointmentStatus],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getService' : IDL.Func([IDL.Text], [Service], ['query']),
  'getServicesByCategory' : IDL.Func(
      [ServiceCategory],
      [IDL.Vec(Service)],
      ['query'],
    ),
  'getServicesByType' : IDL.Func([ServiceType], [IDL.Vec(Service)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAppointmentStatus' : IDL.Func([IDL.Text, AppointmentStatus], [], []),
  'updateService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ServiceCategory, ServiceType, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceCategory = IDL.Variant({
    'pet' : IDL.Null,
    'birdsPoultry' : IDL.Null,
    'smallRuminant' : IDL.Null,
    'largeRuminant' : IDL.Null,
  });
  const Time = IDL.Int;
  const ServiceType = IDL.Variant({
    'vaccination' : IDL.Null,
    'other' : IDL.Null,
    'treatment' : IDL.Null,
    'surgery' : IDL.Null,
    'consultation' : IDL.Null,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Text,
    'status' : AppointmentStatus,
    'clientName' : IDL.Text,
    'preferredDate' : Time,
    'category' : ServiceCategory,
    'serviceId' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'animalType' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : ServiceCategory,
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ServiceCategory,
          IDL.Text,
          Time,
        ],
        [],
        [],
      ),
    'cancelAppointment' : IDL.Func([IDL.Text], [], []),
    'createService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ServiceCategory, ServiceType, IDL.Nat],
        [],
        [],
      ),
    'deleteService' : IDL.Func([IDL.Text], [], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAppointment' : IDL.Func([IDL.Text], [Appointment], ['query']),
    'getAppointmentsByStatus' : IDL.Func(
        [AppointmentStatus],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getService' : IDL.Func([IDL.Text], [Service], ['query']),
    'getServicesByCategory' : IDL.Func(
        [ServiceCategory],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'getServicesByType' : IDL.Func(
        [ServiceType],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAppointmentStatus' : IDL.Func([IDL.Text, AppointmentStatus], [], []),
    'updateService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ServiceCategory, ServiceType, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };