/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : string,
  'status' : AppointmentStatus,
  'clientName' : string,
  'preferredDate' : Time,
  'category' : ServiceCategory,
  'serviceId' : string,
  'phoneNumber' : string,
  'animalType' : string,
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface Service {
  'id' : string,
  'serviceType' : ServiceType,
  'name' : string,
  'description' : string,
  'category' : ServiceCategory,
  'price' : bigint,
}
export type ServiceCategory = { 'pet' : null } |
  { 'birdsPoultry' : null } |
  { 'smallRuminant' : null } |
  { 'largeRuminant' : null };
export type ServiceType = { 'vaccination' : null } |
  { 'other' : null } |
  { 'treatment' : null } |
  { 'surgery' : null } |
  { 'consultation' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'address' : string,
  'phoneNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<
    [string, string, string, string, ServiceCategory, string, Time],
    undefined
  >,
  'cancelAppointment' : ActorMethod<[string], undefined>,
  'createService' : ActorMethod<
    [string, string, string, ServiceCategory, ServiceType, bigint],
    undefined
  >,
  'deleteService' : ActorMethod<[string], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAppointment' : ActorMethod<[string], Appointment>,
  'getAppointmentsByStatus' : ActorMethod<
    [AppointmentStatus],
    Array<Appointment>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getService' : ActorMethod<[string], Service>,
  'getServicesByCategory' : ActorMethod<[ServiceCategory], Array<Service>>,
  'getServicesByType' : ActorMethod<[ServiceType], Array<Service>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAppointmentStatus' : ActorMethod<
    [string, AppointmentStatus],
    undefined
  >,
  'updateService' : ActorMethod<
    [string, string, string, ServiceCategory, ServiceType, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];